### ISSUE TITLE
When Click on Login Button it redirect to sign Up page it should redirect to login Page

### ISSUE THREAD

**Issue by dikshagupta3094** [AbhiDiva96/75per#101]
@AbhiDiva96 
Clicking on login button should redirect to login page instead of signUp Page.
My suggestion is that we should create another button for signUp on Navbar so it would be more convenient for user.
Please assign this issue to me  under GSSOC'24 . 

https://github.com/AbhiDiva96/75per/assets/126059790/29ec6df3-d9e5-4b47-b27d-9a654633b842

**Comment by divyanshu-vashu** [comment]
issue looks simple !!!

i am starting it #101

**Comment by divyanshu-vashu** [comment]
@AbhiDiva96 
hey i fix this issue kindly look on it , and i fixes the button text , which was not changing before based on state of login 

PR #107
