### ISSUE TITLE
[Feature Request]:  Dark Mode for website 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [AbhiDiva96/75per#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will implement the dark mode for the website .

### Use Case

This make the website more attractive 

### Add ScreenShots

![Screenshot 2024-06-15 230400](https://github.com/AbhiDiva96/75per/assets/118350936/b0372e53-38da-4b07-9ed8-f8da15c91455)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AbhiDiva96** [comment]
hey @Ayushmaanagarwal1211 
I have assigned you. make sure the light mode will the same as the current but in dark mode use dark blue. it must be applicable for all the pages.

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
@AbhiDiva96  I have created a dark mode please check the video if you like it then i will raise pr


https://github.com/AbhiDiva96/75per/assets/118350936/5fd634bb-59ec-4d8a-901c-78174bb51779

**Comment by AbhiDiva96** [comment]
Yaah @Ayushmaanagarwal1211 
all good but make sure that lecture card components will be transparent in light blue so that it is visible for user

**Comment by Ayushmaanagarwal1211** [comment]
@AbhiDiva96  I am a little but confused like lecture card component is this 
![Screenshot 2024-06-17 155702](https://github.com/AbhiDiva96/75per/assets/118350936/59627d99-15ce-4ed0-960a-fcc1c2df49c9)

but in this all text can be easily visible but i think you are talking about this quantum component 
![Screenshot 2024-06-17 155652](https://github.com/AbhiDiva96/75per/assets/118350936/c83bd52b-b1ce-4b78-9745-709db5a16065)

IMO the text on the books is not clearly visible

**Comment by AbhiDiva96** [comment]
Make it visible and push it.

**Comment by Ayushmaanagarwal1211** [comment]
Ok
