### ISSUE TITLE
[Bug]: Navbar not responsive in smaller devices

### ISSUE THREAD

**Issue by r7projects-shayan** [AbhiDiva96/75per#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The navbar is not responsive in mobile devices and the buttons are overlapping with each other

### Expected behavior

The navbar should be responsive for all devices and dimensions

### Add ScreenShots

![Screenshot 2024-06-16 183905](https://github.com/AbhiDiva96/75per/assets/167475552/474a090c-a34e-468a-81c8-12879761639c)

### On which device are you experiencing this bug?

Android, iPhone, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by r7projects-shayan** [comment]
@AbhiDiva96 Kindly assign me this issue so that i can work on it

**Comment by AbhiDiva96** [comment]
Hey @r7projects-shayan 
I have assigned you , use sidebar toggler to combine all the side bar elements

**Comment by r7projects-shayan** [comment]
@AbhiDiva96 I will submit within a week
