### ISSUE TITLE
[Feature Request]: add footer to all pages

### ISSUE THREAD

**Issue by kunalmaurya6** [AbhiDiva96/75per#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add footer in all pages

### Use Case

it increases user exprience and connectivity

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AbhiDiva96** [comment]
@kunalmaurya6 
Now you can work on this issue

**Comment by Tanishashrivas** [comment]
I would like to work on this issue and i will do it as soon as it is assigned to me. Please assign this to me under Gssoc'24

**Comment by kunalmaurya6** [comment]
Sorry this issue is resolved #204

**Comment by Tanishashrivas** [comment]
> Sorry this issue is already resolved #204 

Oh okay 😅
