### ISSUE TITLE
want to Improve Ui of Timetable Section

### ISSUE THREAD

**Issue by nishant0708** [AbhiDiva96/75per#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently The Ui of timetable page Looks boring and bad i want to fix that

### Use Case

It will enhance user Experience

### Add ScreenShots

![image](https://github.com/AbhiDiva96/75per/assets/101548649/07aeb611-cc41-416e-aec1-b868b6e84314)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Nihal4777** [comment]
PR merged
