### ISSUE TITLE
[Bug]: Chatbot not getting close on clicking on X

### ISSUE THREAD

**Issue by nishant0708** [AbhiDiva96/75per#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Chatbot not getting close on clicking on X

### Expected behavior

It should Get close

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Nihal4777** [comment]
Sorry @nishant0708. Someone else is already working.
