### ISSUE TITLE
adding Quantum, Lecture, Timetable, PYQ, notes section for 4th year

### ISSUE THREAD

**Issue by anagha-chaudhari** [AbhiDiva96/75per#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

For 4th year there are no such sections, like for other years. I would love to add lecture, timetable, pyq and notes section in the 4th year. Please assign me this under GSSOC'24

### Use Case

It will help viewers find appropriate content for the 4th year just like it does for other years.

### Add ScreenShots

![4th](https://github.com/AbhiDiva96/75per/assets/143149376/4b5dd9a9-4e93-48b6-85de-29b4812c0271)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AbhiDiva96** [comment]
It's completely by someone else already. You can make another issue.
Thanks for your contribution
