### ISSUE TITLE
build the frontend for the previous year question section for the all year 

### ISSUE THREAD

**Issue by AbhiDiva96** [AbhiDiva96/75per#2]
IN the 75per.com 

Build the frontend for the previous year question section . and download button so that a user can download it from the pyq section in a pdf formate.

**Comment by Hitesh4278** [comment]
@AbhiDiva96  can you please add the labels to the issue?

**Comment by AbhiDiva96** [comment]
would you like to work on this issue @Hitesh4278 .
then I will assign it to you

**Comment by Hitesh4278** [comment]
Yes I can work on this. Is it under gssoc?

**Comment by AbhiDiva96** [comment]
yeah man this is under gssoc'24.
have you didn't visited the project page of the gssoc

**Comment by Hitesh4278** [comment]
I have visited that but just confirming this😀. You can assign me this.

**Comment by AbhiDiva96** [comment]
you can start work on it . @Hitesh4278

**Comment by Hitesh4278** [comment]
Thanku👍

**Comment by AbhiDiva96** [comment]
but before working on it you must star and fork the repo. @Hitesh4278

**Comment by Hitesh4278** [comment]
Yes I will do it.

**Comment by Hitesh4278** [comment]
I want to know that is there any specific time period to complete this ?

**Comment by AbhiDiva96** [comment]
Yes, you must have to give the deadline and complete it within your given timeline

**Comment by AbhiDiva96** [comment]
In case any other will submit deadline then I will assigned to that particular one so clear as soon as possible

**Comment by Hitesh4278** [comment]
I have created a pull request for you can check that.

**Comment by musarraf23** [comment]
can you assign this to me ? i can build the frontend for the previous year question section . and download button so that a user can download it from the pyq section in a pdf formate.

**Comment by AbhiDiva96** [comment]
create another issue @musarraf23 
if you want to build.

**Comment by Hitesh4278** [comment]
@AbhiDiva96 then what about the work that is done by me?

**Comment by Hitesh4278** [comment]
@AbhiDiva96  created a new pr you can check that .

**Comment by Nihal4777** [comment]
Closing the issue as the PR is merged.
