### ISSUE TITLE
[Bug]:  change the colour of github icon and footer oftime table section

### ISSUE THREAD

**Issue by ANKeshri** [AbhiDiva96/75per#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- github icon colour is blue which is not its colour and not looking good
- the footer of the timetable setion for 1 st year comes up when we open 

### Expected behavior

- it should be in actual colour of github icon

- footer shoule be fixed at bottom only .

### Add ScreenShots

NOW : 

![Screenshot 2024-06-29 100555](https://github.com/AbhiDiva96/75per/assets/159682348/ba4f15ea-c9c0-4a12-bc60-9e876abbb4f2)

https://github.com/AbhiDiva96/75per/assets/159682348/0c7826bd-9df7-4b94-86bd-5eb81fc03fe1

AFTER : 

![image](https://github.com/AbhiDiva96/75per/assets/159682348/f99e5204-64cc-49e1-818c-932d3dddd5d9)

### On which device are you experiencing this bug?

-laptop 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@AbhiDiva96 PLEASE Assign me this issue under gssoc label 1

**Comment by kunalmaurya6** [comment]
Hi @ANKeshri footer shoule be fixed at bottom only issue is alredy assigned to me #234
