### ISSUE TITLE
UI enhancement required for Lecture page 

### ISSUE THREAD

**Issue by nehashekhawat255** [AbhiDiva96/75per#43]
UI of the lecture page require enhancement, 

- Some space is required in between the lectures and the heading (1st year lecture)
- In one line, 4 lectures will look good with some spaces between them and on left and right side both.
- Lecture boxes will look good with some curves on all the sides.
- Fonts should more attractive then these simple texts
- Name of the lecture will look good in the center and the top and bottom space should be less
- Footer is not added on this page 

Please assign this issue to me under GSSoC'24 and will be happy to hear from you that what I can add more and also subtract from the above mentioned points.

![image](https://github.com/AbhiDiva96/75per/assets/114082299/9ebaad94-92f0-4cd5-8588-62ed8c43f2e9)

**Comment by AbhiDiva96** [comment]
@nehashekhawat255 . you can work on it
