### ISSUE TITLE
Adding return to dashboard Button

### ISSUE THREAD

**Issue by AnanyaJain25** [AbhiDiva96/75per#54]
![Screenshot 2024-05-30 142930](https://github.com/AbhiDiva96/75per/assets/136808696/ee06fcaf-3b3a-449c-87a2-e691c1d7a2be)

![Screenshot 2024-05-30 142859](https://github.com/AbhiDiva96/75per/assets/136808696/9d68587d-a669-4141-a370-799e7cfc8695)
There is no button for user to return back to the dahsboard.

**Comment by adarsh-jha-dev** [comment]
Hey @AnanyaJain25 , I see you have created a couple of more interesting issues, so could you please allow me to work on this one? I am building a very similar project of mine too, so it will help me a lot. It's a request.
