### ISSUE TITLE
UI Updation: Revamping the Landing Page.

### ISSUE THREAD

**Issue by StephenStolk** [AbhiDiva96/75per#6]
The Landing UI should be more visually appealing and promoting the use-cases of the platform. This will create more frequent visiting of the same users. 
Tech stack: Css, Framer Motion, Shadcn ui components (possibility)
Here are a few examples of the sections i am thinking of adding up. 
Note: The overall look will be completely different from the provided samples as it is totally based on the nature and color template of your platform. 

Sample:

Hero Section:
![image](https://github.com/AbhiDiva96/75per/assets/134587780/531dbe87-68bb-4a99-b725-e321c34c3eff)

Service section:
![image](https://github.com/AbhiDiva96/75per/assets/134587780/f6dfbbe2-e514-4eb4-bc10-eb34f4270bef)

I want to grab this issue if approved.

**Comment by StephenStolk** [comment]
I am interested in taking up this issue.

**Comment by AbhiDiva96** [comment]
I think the landing page is ok for now according to the project requirement. u can create a good one.
