### ISSUE TITLE
reDesign the card on lecture page 

### ISSUE THREAD

**Issue by Varsani2520** [AbhiDiva96/75per#69]
redesign this page :
![image](https://github.com/AbhiDiva96/75per/assets/137641079/7a8cc6e1-c0c9-487d-888d-5fa882577259)

here issue is note space between the each card also not hover effect ...

**Comment by Varsani2520** [comment]
Hey @AbhiDiva96 ,
please assign this issue

**Comment by AbhiDiva96** [comment]
already resolved by @nishant0708
