### ISSUE TITLE
Updating UI of Syllabus page

### ISSUE THREAD

**Issue by nishant0708** [AbhiDiva96/75per#7]
The Ui of syllabus Page does not looks good and its need an upgrade . I can work on it please assign me under Gssoc 24
![image](https://github.com/AbhiDiva96/75per/assets/101548649/0c2fda68-3c51-4afd-a422-6693514a2605)

**Comment by AbhiDiva96** [comment]
I assined it to you can you give me sample how actually you want to build this page.

**Comment by nishant0708** [comment]
Actully i have not designed something but i will go with the flow for that .. but for sure page needs better icons.. but yeah in the end It will look good for sure .. but if you want to get idea about my UI ..you can checkout these websites i have created
https://www.tedxdavv.in/
https://niko-portfolio.vercel.app/
