### ISSUE TITLE
Correction in contributing.md file

### ISSUE THREAD

**Issue by PradnyaGaitonde** [AbhiDiva96/75per#91]
There are a few necessary corrections to be made in the contributing.md file.
Please assign me this issue under gssoc24.

**Comment by AbhiDiva96** [comment]
hey @PradnyaGaitonde 
what correction you want to make pls mention here

**Comment by PradnyaGaitonde** [comment]
@AbhiDiva96 The repository name mentioned in the contributing.md file is wrong. Would like to correct it.
![image](https://github.com/AbhiDiva96/75per/assets/116059908/3716e894-c6ef-4f3b-b34e-550bc97d9a1a)
